### ISSUE TITLE
Wifi error

### ISSUE THREAD

**Issue by sunsettrack4** [sunsettrack4/resurrection_device_samsung_slte#2]
The device is unable to turn on Wifi.

**Comment by SerenityS** [comment]
using this defconfig
https://github.com/SerenityS/android_kernel_samsung_slte/commit/c42a720c363353b7af58d8ac6adad4f7dff746ee

I build with your source, but wifi work perpectly.

**Comment by sunsettrack4** [comment]
Thanks for your reply! I'm building RR again right now. Your kernel commit is included.

**Comment by sunsettrack4** [comment]
Did you build CyanogenMod or ResurrectionRemix ROM?

**Comment by SerenityS** [comment]
I build CM

**Comment by sunsettrack4** [comment]
Do you also use TWRP 2.8.7.0 provided by modpunk for flashing the ROM?

**Comment by SerenityS** [comment]
No I use another user's twrp for G850S

**Comment by sunsettrack4** [comment]
Thanks for your efforts! :)
Wifi is fixed after applying the kernel change.
